### ISSUE TITLE
Remove data referring to specific developer portal

### ISSUE THREAD

**Issue by mpguerra** [kevprice83/activedocs-keycloak-client#1]
e.g https://github.com/kevprice83/activedocs-keycloak-client/blob/e448b3dfd506557200e0e5a83a9ec7b6e8262b32/auth.js#L36

**Comment by kevprice83** [comment]
Yeah this can be converted to some liquid to get this value I'm sure.

**Comment by mpguerra** [comment]
Also the swagger spec: https://github.com/kevprice83/activedocs-keycloak-client/blob/e448b3dfd506557200e0e5a83a9ec7b6e8262b32/docs.html.liquid#L26
